name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win-mac:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        platform: [windows, macosx]
        arch: [x64, x86]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build
        run: |
          xmake f -p ${{ matrix.platform }} -a ${{ matrix.arch }} -m release -y
          xmake build -y webview_shared

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "webview-win64"
          path: ./build/${{ matrix.platform }}/${{ matrix.arch }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build
        run: |
          xmake f -p linux -a x64 -m release -y
          xmake build -y webview_shared
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "webview-linux64"
          path: ./build/linux